// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDOkE1Dl6MDzW481X2Oascml9YAXo_inA0',
    appId: '1:1075040481167:web:85bba0fe78f74d7043e5fa',
    messagingSenderId: '1075040481167',
    projectId: 'final-dear-diary-project',
    authDomain: 'final-dear-diary-project.firebaseapp.com',
    storageBucket: 'final-dear-diary-project.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCkZ3cz2VzJ-fOCTmilVy9Jk6POhU2U_LU',
    appId: '1:1075040481167:android:a5fc3ca7fda63b9143e5fa',
    messagingSenderId: '1075040481167',
    projectId: 'final-dear-diary-project',
    storageBucket: 'final-dear-diary-project.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD_11XpWaSB2J3wD1YzifGKpy3lmXYJPNc',
    appId: '1:1075040481167:ios:ea186f3c619f229e43e5fa',
    messagingSenderId: '1075040481167',
    projectId: 'final-dear-diary-project',
    storageBucket: 'final-dear-diary-project.appspot.com',
    iosBundleId: 'com.alireza.dearDiaryWithFirebaseAuthStorageDatabase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD_11XpWaSB2J3wD1YzifGKpy3lmXYJPNc',
    appId: '1:1075040481167:ios:ae6bc57f9ffd849b43e5fa',
    messagingSenderId: '1075040481167',
    projectId: 'final-dear-diary-project',
    storageBucket: 'final-dear-diary-project.appspot.com',
    iosBundleId: 'com.alireza.dearDiaryWithFirebaseAuthStorageDatabase.RunnerTests',
  );
}
